<a href="https://colab.research.google.com/github/Himkeshtak/Deep-Learning/blob/main/PyTorch%20for%20Deep%20learning%20dataset_and_dataloader_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
# Step 1: Create a synthetic classification dataset using the sklearn
x, y = make_classification(
    n_samples=100,     # NUmber of samples
    n_features=4,     #Number of features
    n_informative=4,  #Number of informative features
    n_redundant=0,    #Number of redundant features
    n_classes=2,      # NUmber of classes
    random_state=42   # For reproducibility
)


In [ ]:
x

array([[-3.98388793e-01,  2.20986914e-01, -1.85561668e-01,
         1.00771366e+00],
       [-4.14657549e-01,  2.03326684e+00,  4.89787011e-01,
         5.35130464e-01],
       [-1.92349100e+00,  8.94757682e-01,  1.30128825e+00,
        -1.53406432e+00],
       [-3.12096434e+00, -3.17250750e+00, -2.59824281e+00,
        -3.13420280e+00],
       [-1.66476892e+00,  1.71161946e+00,  1.74676195e+00,
        -1.01607532e+00],
       [ 1.37494797e-01,  1.69739499e+00, -3.19247925e-01,
         7.04069672e-01],
       [-3.56759206e+00, -1.31725220e+00,  1.27171688e+00,
        -3.12210932e+00],
       [ 3.32519447e-01, -2.23013398e+00,  8.68629755e-01,
         1.20624516e+00],
       [ 1.95949858e+00,  1.25752701e+00, -1.31131901e+00,
        -1.35484635e+00],
       [-1.37875887e+00, -1.03451357e+00, -8.37070289e-01,
        -2.22592518e+00],
       [-1.39385954e-01,  1.55332227e+00, -8.22019454e-02,
        -1.01875280e+00],
       [-1.16810306e+00,  7.06758414e-01, -1.24656588e+00,
      

In [ ]:
x.shape

(100, 4)

In [ ]:
y


array([1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
# convert the data to Pytorch tensors

x = torch.tensor(x, dtype = torch.float32)
y = torch.tensor(y, dtype= torch.long)


In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
x


tensor([[-3.9839e-01,  2.2099e-01, -1.8556e-01,  1.0077e+00],
        [-4.1466e-01,  2.0333e+00,  4.8979e-01,  5.3513e-01],
        [-1.9235e+00,  8.9476e-01,  1.3013e+00, -1.5341e+00],
        [-3.1210e+00, -3.1725e+00, -2.5982e+00, -3.1342e+00],
        [-1.6648e+00,  1.7116e+00,  1.7468e+00, -1.0161e+00],
        [ 1.3749e-01,  1.6974e+00, -3.1925e-01,  7.0407e-01],
        [-3.5676e+00, -1.3173e+00,  1.2717e+00, -3.1221e+00],
        [ 3.3252e-01, -2.2301e+00,  8.6863e-01,  1.2062e+00],
        [ 1.9595e+00,  1.2575e+00, -1.3113e+00, -1.3548e+00],
        [-1.3788e+00, -1.0345e+00, -8.3707e-01, -2.2259e+00],
        [-1.3939e-01,  1.5533e+00, -8.2202e-02, -1.0188e+00],
        [-1.1681e+00,  7.0676e-01, -1.2466e+00, -1.5512e+00],
        [-3.4136e-01,  1.3581e+00,  1.9602e+00, -1.5211e+00],
        [-2.3727e-01, -7.0154e-01, -1.5967e+00, -4.7554e-01],
        [-3.8796e-01,  1.8651e+00, -7.5390e-01, -1.5325e-02],
        [-6.7910e-01,  1.9993e+00,  1.2292e+00, -5.3726e-01],
        

In [ ]:
y

tensor([1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
        0, 0, 0, 0])

In [ ]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [ ]:
dataset = CustomDataset(x,y)

In [ ]:
len(dataset)

100

In [ ]:
dataset[2]

(tensor([-1.9235,  0.8948,  1.3013, -1.5341]), tensor(0))

In [ ]:
dataloader = DataLoader(dataset, batch_size=5, shuffle=True)

In [ ]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("😂"*50)

tensor([[-0.3357,  0.9598, -1.0046,  0.9375],
        [-1.3788, -1.0345, -0.8371, -2.2259],
        [-2.2542,  0.3824,  2.5854, -1.9502],
        [ 0.9464, -3.7349,  1.6037,  1.2771],
        [-3.0053, -0.7115, -1.9889, -2.6770]])
tensor([0, 1, 0, 1, 1])
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂
tensor([[-1.8772,  1.4187,  1.9864, -1.9964],
        [-0.1394,  1.5533, -0.0822, -1.0188],
        [-0.8955, -1.4850, -1.4542, -1.8089],
        [-1.1054,  0.8496, -1.2899, -1.5738],
        [ 2.3861, -1.8411,  1.9042,  1.0020]])
tensor([0, 1, 0, 1, 1])
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂
tensor([[-2.3276, -0.4521, -0.8776, -2.3092],
        [ 0.8786,  0.0953,  0.2035, -0.1335],
        [-1.7542,  1.6572,  3.6294, -2.2735],
        [ 2.3315, -0.5790,  1.6648,  0.9114],
        [-3.1210, -3.1725, -2.5982, -3.1342]])
tensor([0, 0, 0, 1, 0])
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂
tensor([[ 0.0382,  2.4684, -0.7156,  0.4083],
        [ 1.0317,  1.2444, -0.3299, 