<a href="https://colab.research.google.com/github/Himkeshtak/Deep-Learning/blob/main/PyTorch%20for%20Deep%20learning/PyTorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__() #with the help of this the child class invokes the parent class
    #into the scene
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()
    #self.ReLU = nn.ReLU()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)
   # out = self.ReLU(out)

    return out

In [9]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
#model.forward(features) , we can do this too but this is not recommended

model(features)


tensor([[0.5094],
        [0.5127],
        [0.5994],
        [0.4955],
        [0.5141],
        [0.5252],
        [0.3995],
        [0.5929],
        [0.5852],
        [0.5365]], grad_fn=<SigmoidBackward0>)

In [10]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3775, -0.4070,  0.3714, -0.1917, -0.4447]], requires_grad=True)

In [11]:
# model bias
model.linear.bias #as name of our model we have choosen is linear , there fore we call
#call it in such fashion

Parameter containing:
tensor([0.1037], requires_grad=True)

In [13]:
# to visualize our model , as we done in the keras
!pip install torchinfo


In [14]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [16]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__() #with the help of this the child class invokes the parent
    # class into the scene
    self.linear1 = nn.Linear(num_features,3) #layer 1 has 3 neurons
    self.ReLU = nn.ReLU()
    self.linear2 = nn.Linear(3,1) # this is layer-2 which is getting 3 inputs
    # from the past layer (of 3 neurons), and itself has 1 neuron and hence giving
    # 1 output from this layer , thats what the 3, 1 means
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.ReLU(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
   # out = self.ReLU(out)

    return out

In [17]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
#model.forward(features) , we can do this too but this is not recommended

model(features)


tensor([[0.5331],
        [0.5568],
        [0.5464],
        [0.5650],
        [0.5396],
        [0.5304],
        [0.5324],
        [0.5426],
        [0.5540],
        [0.5598]], grad_fn=<SigmoidBackward0>)

In [18]:
print (model.linear1.weight)
print (model.linear2.weight)
print (model.linear1.bias)
print (model.linear2.bias)


Parameter containing:
tensor([[ 0.1075,  0.3276,  0.2710,  0.1306, -0.4152],
        [-0.3718, -0.3671, -0.0145, -0.3868, -0.1132],
        [ 0.0403,  0.3907, -0.2768,  0.2821, -0.3837]], requires_grad=True)
Parameter containing:
tensor([[-0.5168,  0.4022,  0.2757]], requires_grad=True)
Parameter containing:
tensor([-0.3615,  0.1703,  0.3382], requires_grad=True)
Parameter containing:
tensor([0.1110], requires_grad=True)


In [19]:
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Now easy method to use the make the calss in which there is no need of lot of variables we made for each and every layer , just use the Sequential

In [21]:
class Model(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

and now also you can get the same out as before, tom run just copy paste the above code blocks below

Important parameters

In [ ]:
lr =0.01
epochs = 25

In [24]:
# define loss function
loss_function = nn.BCELoss()

Training Pipeline

In [25]:
model = MySimpleNN(x_train_tensor.shape[1])

#use the optimzer of gradient decsect to prevent from
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)
# SGD = Stochastic Gradient Descent

for epoch in range(epochs):

  #forward pass
  y_pred = model(features)

  #loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  #clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update by SGD
  optimizer.step()


  #print loss in each epoch

  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


NameError: name 'y_train_tensor' is not defined

Model Evaluation

In [ ]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')