<a href="https://colab.research.google.com/github/Himkeshtak/Deep-Learning/blob/main/PyTorch%20for%20Deep%20learning/Tensors_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import torch
print(torch.__version__)

2.9.0+cu126


In [46]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")


GPU is available!
using GPU: Tesla T4


Creating Tensors

In [47]:
#using empty (this just allocates the memory )
a = torch.empty(3,4)

In [48]:
#check type (tell about the type of thing we made)
type(a)

torch.Tensor

In [49]:
#using Rand (Gives matrix of random values , all will be normalized one)
torch.rand(2,3)

tensor([[0.5782, 0.7536, 0.1093],
        [0.4771, 0.1076, 0.9829]])

In [50]:
#use of seed
torch.rand(2,3)

tensor([[0.1483, 0.5956, 0.3634],
        [0.7842, 0.5017, 0.4497]])

In [51]:
#manually seeeding the random values so that they dont change on each execution \

torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [52]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [53]:
#using tensor
torch.tensor([[1,10,11],[2, 5, 6]])

tensor([[ 1, 10, 11],
        [ 2,  5,  6]])

In [54]:
# a range , gives a tensor between the given range in the given repeatation freq
print("using arange ->", torch.arange(0,10,2))

#using linspace, gives linearly space numbers in the tensor in tbhe given range
print("using linspace ->", torch.linspace(0,10,10))

#using eye, gives the identity matrix of input shape
print ("using eye ->", torch.eye(5))

#using full, makes the matrix of input dimension consisiting of single input elelment
print("using full ->", torch.full((3,3),5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor shape

In [55]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [56]:
#to find the shape
x.shape

torch.Size([2, 3])

In [57]:
#it will have similar shape of like x
torch.empty_like(x)

tensor([[493921239150, 489626271855, 390842023976],
        [210453397595, 214748364844, 219043332140]])

In [58]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [59]:
torch.rand_like(x, dtype = torch.float32)
# it happened beacuse in the x tensor we have all the tensors , bu rand generate all the float

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

Tensor Data types  

In [60]:
#find data type
x.dtype

torch.int64

In [61]:
#assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [62]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [63]:
# convert the datatype of the given datatype
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

Mathematical operations on Tensors

In [64]:
y = torch.rand(2,2)

In [65]:
#addition
y+2

#subtraction
y-2

#multiply
y * 3

#division

y  / 3

#int division
(y*100)//3

#mod
y%2

#power

y**2

tensor([[0.4957, 0.3105],
        [0.4842, 0.9701]])

Element wise operations

In [66]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2924, 0.4823, 0.6150],
        [0.4967, 0.4521, 0.0575]])
tensor([[0.0687, 0.0501, 0.0108],
        [0.0343, 0.1212, 0.0490]])


In [67]:
#add
print(a+b)

#sub
print(a-b)

#multi
print(a*b)

#division
print(a/b)

#power
print(a**b)

tensor([[0.3611, 0.5324, 0.6257],
        [0.5311, 0.5733, 0.1065]])
tensor([[0.2237, 0.4323, 0.6042],
        [0.4624, 0.3309, 0.0085]])
tensor([[0.0201, 0.0242, 0.0066],
        [0.0171, 0.0548, 0.0028]])
tensor([[ 4.2560,  9.6331, 57.1744],
        [14.4714,  3.7297,  1.1731]])
tensor([[0.9190, 0.9642, 0.9948],
        [0.9763, 0.9083, 0.8693]])


In [68]:
c = torch.tensor([1, -2, 3, -4])

In [69]:
# find the absolute of the tensor
torch.abs(c)


tensor([1, 2, 3, 4])

In [70]:
#find the negative od the tensor
torch.neg(c)

tensor([-1,  2, -3,  4])

In [71]:
d = torch.tensor([1.9, 1.5, 2.1, 3.4])

In [72]:
# finds the round off of the elementsof the matrix
torch.round(d)

tensor([2., 2., 2., 3.])

In [73]:
# ceil upper wale integer ki taraf round off
torch.ceil(d)

tensor([2., 2., 3., 4.])

In [74]:
#floor, piche wale integer ki taraf round off ho jayega
torch.floor(d)

tensor([1., 1., 2., 3.])

In [75]:
#clamp , it keeps our elements in the input given range
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.0000, 2.1000, 3.0000])

Reduction operation

In [76]:
e = torch.randint(size=(2,3), low=0, high=10, dtype = torch.float32)
e

tensor([[9., 4., 4.],
        [5., 4., 0.]])

In [77]:
#sum
print(torch.sum(e))

#sum along the columns
print(torch.sum(e, dim=0))

#sum along rows
print(torch.sum(e, dim=1))



tensor(26.)
tensor([14.,  8.,  4.])
tensor([17.,  9.])


In [78]:
#mean , of all the elements of tensor
print(torch.mean(e))
#mean along the columns
torch.mean(e, dim=0)


tensor(4.3333)


tensor([7., 4., 2.])

In [79]:
#median
torch.median(e)

tensor(4.)

In [80]:
#max and min
print(torch.max(e))
print(torch.min(e))


tensor(9.)
tensor(0.)


In [81]:
#finds the product of all the elements
torch.prod(e)

tensor(0.)

In [82]:
#standard deviation
torch.std(e)

tensor(2.8752)

In [83]:
#Variance
torch.var(e)

tensor(8.2667)

In [84]:
#argmax, tells about the pos of the max arg
torch.argmax(e)

tensor(0)

In [85]:
torch.argmin(e)

tensor(5)

Matrix operation

In [86]:
f = torch.randint(size=(2,3), low = 0,high=10, dtype = torch.float32)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8., 9., 3.],
        [0., 9., 3.]])
tensor([[7, 9],
        [5, 2],
        [9, 6]])


In [87]:
#matrix multiplication
#torch.matmul(f,g)

In [88]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

#dot product

In [89]:
torch.sigmoid(f )

tensor([[0.9997, 0.9999, 0.9526],
        [0.5000, 0.9999, 0.9526]])

In [90]:
torch.softmax(f, dim=0)

tensor([[9.9966e-01, 5.0000e-01, 5.0000e-01],
        [3.3535e-04, 5.0000e-01, 5.0000e-01]])

Copying a Tensor

In [91]:
a = torch.rand(2,3)
a

tensor([[0.5782, 0.7536, 0.1093],
        [0.4771, 0.1076, 0.9829]])

In [92]:
b=a
b
#but as we change the value of a value of b goes changed automatically

tensor([[0.5782, 0.7536, 0.1093],
        [0.4771, 0.1076, 0.9829]])

In [93]:
b = a.clone()

In [94]:
a

tensor([[0.5782, 0.7536, 0.1093],
        [0.4771, 0.1076, 0.9829]])

In [95]:
b

tensor([[0.5782, 0.7536, 0.1093],
        [0.4771, 0.1076, 0.9829]])

In [96]:
a[0][0] = 10

In [97]:
a

tensor([[10.0000,  0.7536,  0.1093],
        [ 0.4771,  0.1076,  0.9829]])

In [98]:
b

tensor([[0.5782, 0.7536, 0.1093],
        [0.4771, 0.1076, 0.9829]])

In [99]:
id(a)

140050189308928

In [100]:
id(b)

140050218904112

Tensor operations on GPU

In [101]:
torch.cuda.is_available()

True

In [102]:
device = torch.device('cuda')

In [103]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.9835, 0.2422, 0.7872],
        [0.0981, 0.6317, 0.2422]], device='cuda:0')

In [105]:
#moving an existing tensor on  CPU to GPU
a = torch.rand(2,3)
a

tensor([[0.8660, 0.9567, 0.1371],
        [0.0177, 0.5417, 0.6575]])

In [106]:
b = a.to(device)

In [107]:
b+5

tensor([[5.8660, 5.9567, 5.1371],
        [5.0177, 5.5417, 5.6575]], device='cuda:0')

In [1]:
import torch
import time

#define the size of the matrix
size = 10000

#create the matrix on the CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

#measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f}seconds")

#move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

#measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

#compare results
print("\nSpeedup (CPU time/GPU tmie): ", cpu_time/gpu_time)

print(f"Time on GPU: {gpu_time:.4f} seconds")

Time on CPU: 19.0647seconds

Speedup (CPU time/GPU tmie):  29.84480693615298
Time on GPU: 0.6388 seconds


Reshaping tensors

In [2]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [4]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
b = torch.rand(2,3,4)
b

tensor([[[0.6442, 0.2755, 0.1683, 0.6062],
         [0.9170, 0.7219, 0.7543, 0.0265],
         [0.8919, 0.5776, 0.6710, 0.9477]],

        [[0.7447, 0.6758, 0.3169, 0.0713],
         [0.7752, 0.9168, 0.0026, 0.2345],
         [0.6236, 0.4376, 0.4216, 0.9893]]])

In [6]:
#permute
b.permute(2, 1,0).shape

torch.Size([4, 3, 2])

In [7]:
#unsqueeze
#image size
c = torch.rand(226,226,3)
c.unsqueeze(dim = 0).shape

torch.Size([1, 226, 226, 3])

In [8]:
#squeeze
d = torch.rand(1,20)
d.squeeze(dim=0).shape

torch.Size([20])

NumPy and Pytorch

In [9]:
import numpy as np


In [10]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [12]:
b = a.numpy()
b

array([1, 2, 3])

In [13]:
type(b)

numpy.ndarray

In [14]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [15]:
torch.from_numpy(c)

tensor([1, 2, 3])